export interface ProductDefinition {
  id: string;
  name: string;
  unitAmount: number;
  currency: string;
  interval: "month" | "year" | null;
  category: string;
  stripeProductName?: string;
}

export const PRODUCTS: Record<string, ProductDefinition> = {
  "cch-unlimited-safety": {
    id: "cch-unlimited-safety",
    name: "Unlimited Safety",
    unitAmount: 9900,
    currency: "usd",
    interval: "month",
    category: "CCHUB Corey",
    stripeProductName: "Unlimited Safety",
  },
  "iso-essentials": {
    id: "iso-essentials",
    name: "ISO Essentials",
    unitAmount: 4900,
    currency: "usd",
    interval: "month",
    category: "ACSI ISO",
    stripeProductName: "ISO Essentials",
  },
  "iso-professional": {
    id: "iso-professional",
    name: "ISO Professional",
    unitAmount: 14900,
    currency: "usd",
    interval: "month",
    category: "ACSI ISO",
    stripeProductName: "ISO Professional",
  },
  "integrated-enterprise": {
    id: "integrated-enterprise",
    name: "Integrated Enterprise",
    unitAmount: 29900,
    currency: "usd",
    interval: "month",
    category: "ACSI ISO",
    stripeProductName: "Integrated Enterprise",
  },
  "bma-subscription": {
    id: "bma-subscription",
    name: "Spanish Bilingual Medical Assistant",
    unitAmount: 19900,
    currency: "usd",
    interval: "month",
    category: "Specialized",
    stripeProductName: "Bilingual",
  },
  "expert-retainer": {
    id: "expert-retainer",
    name: "Human Expert Retainer",
    unitAmount: 49900,
    currency: "usd",
    interval: "month",
    category: "Specialized",
    stripeProductName: "Expert Retainer",
  },
  "brandnswag-platform": {
    id: "brandnswag-platform",
    name: "BrandNSwag Platform",
    unitAmount: 4900,
    currency: "usd",
    interval: "month",
    category: "BrandNSwag",
    stripeProductName: "BrandNSwag",
  },
  "mentorship-foundation": {
    id: "mentorship-foundation",
    name: "ACSI Mentorship — Foundation",
    unitAmount: 250000,
    currency: "usd",
    interval: null,
    category: "ACSI Mentorship",
    stripeProductName: "Foundation",
  },
  "mentorship-executive": {
    id: "mentorship-executive",
    name: "ACSI Mentorship — Executive",
    unitAmount: 500000,
    currency: "usd",
    interval: null,
    category: "ACSI Mentorship",
    stripeProductName: "Executive",
  },
  "course-dot-medical": {
    id: "course-dot-medical",
    name: "DOT Medical Certification Course",
    unitAmount: 19900,
    currency: "usd",
    interval: null,
    category: "Training",
    stripeProductName: "DOT Medical",
  },
  "course-osha-surveillance": {
    id: "course-osha-surveillance",
    name: "OSHA Medical Surveillance Course",
    unitAmount: 24900,
    currency: "usd",
    interval: null,
    category: "Training",
    stripeProductName: "OSHA Medical",
  },
  "course-osha-medical": {
    id: "course-osha-medical",
    name: "OSHA Medical Surveillance Course",
    unitAmount: 24900,
    currency: "usd",
    interval: null,
    category: "Training",
    stripeProductName: "OSHA Medical",
  },
  "course-drug-alcohol": {
    id: "course-drug-alcohol",
    name: "Drug & Alcohol Testing Course",
    unitAmount: 19900,
    currency: "usd",
    interval: null,
    category: "Training",
    stripeProductName: "Drug",
  },
  "course-iso-management": {
    id: "course-iso-management",
    name: "ISO Management Systems Course",
    unitAmount: 34900,
    currency: "usd",
    interval: null,
    category: "Training",
    stripeProductName: "ISO Management",
  },
  "course-osha-recordkeeping": {
    id: "course-osha-recordkeeping",
    name: "OSHA Recordkeeping Master Course",
    unitAmount: 29900,
    currency: "usd",
    interval: null,
    category: "Training",
    stripeProductName: "Recordkeeping",
  },
  "course-complete-bundle": {
    id: "course-complete-bundle",
    name: "Complete Training Bundle",
    unitAmount: 89900,
    currency: "usd",
    interval: null,
    category: "Training",
    stripeProductName: "Complete",
  },
};
