import { useRef } from "react";
import { X, Printer, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";

// ── Types ─────────────────────────────────────────────────────────────────────
type PestleItem = { text: string; type: "risk" | "opportunity" };
type PestleData = Record<string, PestleItem[]>;
type SwotData = { strengths: string[]; weaknesses: string[]; opportunities: string[]; threats: string[] };
type InterestedParty = {
  id: string; party: string; group: "internal" | "external"; relevant: boolean;
  needs: string; expectations: string; actions: string; monitoringMethod: string;
  risks: string; opportunities: string;
  piRanking: "manage_closely" | "keep_informed" | "keep_satisfied" | "monitor_only" | "";
};

interface PrintDocsProps {
  docType: "pestle" | "swot" | "parties" | null;
  onClose: () => void;
  orgName?: string | null;
  standard?: string | null;
  pestle: PestleData;
  swot: SwotData;
  parties: InterestedParty[];
}

const PESTLE_ORDER = ["political", "economic", "social", "technological", "legal", "environmental"];
const PESTLE_LABELS: Record<string, string> = {
  political: "Political", economic: "Economic", social: "Social",
  technological: "Technological", legal: "Legal", environmental: "Environmental",
};

const PIR_LABELS: Record<string, string> = {
  manage_closely: "Manage Closely",
  keep_informed: "Keep Informed",
  keep_satisfied: "Keep Satisfied",
  monitor_only: "Monitor Only",
};

function todayStr() {
  return new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

// ── Shared print header ────────────────────────────────────────────────────────
function DocHeader({ title, subtitle, orgName, standard, docRef }: {
  title: string; subtitle: string; orgName?: string | null; standard?: string | null; docRef: string;
}) {
  return (
    <div style={{ borderBottom: "3px solid #1e3a5f", marginBottom: 24, paddingBottom: 16 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        <div>
          <div style={{ fontSize: 9, fontWeight: 700, color: "#ea6c19", letterSpacing: 2, textTransform: "uppercase", marginBottom: 4 }}>
            ACSI ISO Manager · Core Compliance Hub
          </div>
          <h1 style={{ fontSize: 22, fontWeight: 900, color: "#1e3a5f", margin: "0 0 2px 0", letterSpacing: -0.5 }}>
            {title}
          </h1>
          <p style={{ fontSize: 11, color: "#64748b", margin: 0 }}>{subtitle}</p>
        </div>
        <div style={{ textAlign: "right", fontSize: 10, color: "#64748b", lineHeight: 1.8 }}>
          <div><strong style={{ color: "#1e3a5f" }}>Organization:</strong> {orgName || "—"}</div>
          <div><strong style={{ color: "#1e3a5f" }}>Standard:</strong> {standard || "ISO 9001"}</div>
          <div><strong style={{ color: "#1e3a5f" }}>Date:</strong> {todayStr()}</div>
          <div><strong style={{ color: "#1e3a5f" }}>Doc Ref:</strong> {docRef}</div>
        </div>
      </div>
    </div>
  );
}

function DocFooter() {
  return (
    <div style={{ borderTop: "1px solid #e2e8f0", marginTop: 32, paddingTop: 10, display: "flex", justifyContent: "space-between", fontSize: 8, color: "#94a3b8" }}>
      <span>Generated by ACSI ISO Manager · Core Compliance Hub · corecompliancehub.com</span>
      <span>Printed {todayStr()} · Confidential</span>
    </div>
  );
}

// ── PESTLE Document ────────────────────────────────────────────────────────────
function PestleDocument({ orgName, standard, pestle }: { orgName?: string | null; standard?: string | null; pestle: PestleData }) {
  const rows: { category: string; text: string; type: "risk" | "opportunity" }[] = [];
  PESTLE_ORDER.forEach(key => {
    (pestle[key] || []).forEach(item => {
      rows.push({ category: PESTLE_LABELS[key], text: item.text, type: item.type });
    });
  });

  const riskCount = rows.filter(r => r.type === "risk").length;
  const oppCount = rows.filter(r => r.type === "opportunity").length;

  return (
    <div style={{ fontFamily: "'Segoe UI', Arial, sans-serif", fontSize: 11, color: "#0f172a", width: "100%" }}>
      <DocHeader
        title="PESTLE Analysis"
        subtitle="External Issues Register — ISO Clause 4.1"
        orgName={orgName}
        standard={standard}
        docRef="ISO-CTXT-4.1-P"
      />

      {/* Summary strip */}
      <div style={{ display: "flex", gap: 16, marginBottom: 20 }}>
        {[
          { label: "Total Factors", value: rows.length, color: "#1e3a5f" },
          { label: "Risks", value: riskCount, color: "#dc2626" },
          { label: "Opportunities", value: oppCount, color: "#16a34a" },
        ].map(s => (
          <div key={s.label} style={{ flex: 1, border: "1px solid #e2e8f0", borderRadius: 8, padding: "10px 14px", textAlign: "center" }}>
            <div style={{ fontSize: 20, fontWeight: 900, color: s.color }}>{s.value}</div>
            <div style={{ fontSize: 9, fontWeight: 600, color: "#64748b", textTransform: "uppercase", letterSpacing: 1 }}>{s.label}</div>
          </div>
        ))}
      </div>

      {/* Table */}
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 10 }}>
        <thead>
          <tr style={{ backgroundColor: "#1e3a5f" }}>
            <th style={{ padding: "10px 12px", color: "#fff", textAlign: "left", fontWeight: 700, width: "18%", fontSize: 10 }}>Category</th>
            <th style={{ padding: "10px 12px", color: "#fff", textAlign: "left", fontWeight: 700, fontSize: 10 }}>Factor / Issue</th>
            <th style={{ padding: "10px 12px", color: "#fff", textAlign: "center", fontWeight: 700, width: "12%", fontSize: 10 }}>Classification</th>
          </tr>
        </thead>
        <tbody>
          {rows.length === 0 ? (
            <tr>
              <td colSpan={3} style={{ padding: "20px 12px", textAlign: "center", color: "#94a3b8", fontStyle: "italic" }}>
                No factors recorded yet.
              </td>
            </tr>
          ) : (
            rows.map((row, i) => (
              <tr key={i} style={{ backgroundColor: i % 2 === 0 ? "#f8fafc" : "#fff", borderBottom: "1px solid #e2e8f0" }}>
                <td style={{ padding: "9px 12px", fontWeight: 700, color: "#1e3a5f", verticalAlign: "top" }}>{row.category}</td>
                <td style={{ padding: "9px 12px", color: "#334155", verticalAlign: "top", lineHeight: 1.5 }}>{row.text}</td>
                <td style={{ padding: "9px 12px", textAlign: "center", verticalAlign: "top" }}>
                  <span style={{
                    display: "inline-block",
                    padding: "3px 8px",
                    borderRadius: 12,
                    fontSize: 9,
                    fontWeight: 700,
                    letterSpacing: 0.5,
                    backgroundColor: row.type === "risk" ? "#fee2e2" : "#dcfce7",
                    color: row.type === "risk" ? "#dc2626" : "#16a34a",
                    border: `1px solid ${row.type === "risk" ? "#fca5a5" : "#86efac"}`,
                  }}>
                    {row.type === "risk" ? "RISK" : "OPPORTUNITY"}
                  </span>
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>

      {/* Per-category summary */}
      <div style={{ marginTop: 24 }}>
        <h3 style={{ fontSize: 11, fontWeight: 700, color: "#1e3a5f", marginBottom: 10, borderBottom: "1px solid #e2e8f0", paddingBottom: 6 }}>
          Category Summary
        </h3>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 8 }}>
          {PESTLE_ORDER.map(key => {
            const items = pestle[key] || [];
            const r = items.filter(i => i.type === "risk").length;
            const o = items.filter(i => i.type === "opportunity").length;
            return (
              <div key={key} style={{ border: "1px solid #e2e8f0", borderRadius: 6, padding: "8px 10px" }}>
                <div style={{ fontWeight: 700, fontSize: 10, color: "#1e3a5f", marginBottom: 4 }}>{PESTLE_LABELS[key]}</div>
                <div style={{ display: "flex", gap: 8, fontSize: 9 }}>
                  <span style={{ color: "#dc2626", fontWeight: 600 }}>{r} Risk{r !== 1 ? "s" : ""}</span>
                  <span style={{ color: "#16a34a", fontWeight: 600 }}>{o} Opp{o !== 1 ? "s" : ""}</span>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <DocFooter />
    </div>
  );
}

// ── SWOT Document ──────────────────────────────────────────────────────────────
function SwotDocument({ orgName, standard, swot }: { orgName?: string | null; standard?: string | null; swot: SwotData }) {
  const quadrants = [
    { key: "strengths",     label: "Strengths",     subtitle: "Internal Advantages",  headerBg: "#15803d", lightBg: "#f0fdf4", borderColor: "#86efac", items: swot.strengths },
    { key: "weaknesses",    label: "Weaknesses",    subtitle: "Internal Gaps",        headerBg: "#b91c1c", lightBg: "#fef2f2", borderColor: "#fca5a5", items: swot.weaknesses },
    { key: "opportunities", label: "Opportunities", subtitle: "External Upside",      headerBg: "#1d4ed8", lightBg: "#eff6ff", borderColor: "#93c5fd", items: swot.opportunities },
    { key: "threats",       label: "Threats",       subtitle: "External Risks",       headerBg: "#92400e", lightBg: "#fffbeb", borderColor: "#fcd34d", items: swot.threats },
  ];

  const total = Object.values(swot).reduce((a, b) => a + b.length, 0);

  return (
    <div style={{ fontFamily: "'Segoe UI', Arial, sans-serif", fontSize: 11, color: "#0f172a", width: "100%" }}>
      <DocHeader
        title="SWOT Analysis"
        subtitle="Internal Issues Register — ISO Clause 4.1"
        orgName={orgName}
        standard={standard}
        docRef="ISO-CTXT-4.1-S"
      />

      <div style={{ marginBottom: 16, fontSize: 10, color: "#64748b", fontStyle: "italic" }}>
        {total} total factors identified · Internal issues that feed into Clause 6.1 Risk Planning
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
        {quadrants.map(q => (
          <div key={q.key} style={{ border: `1px solid ${q.borderColor}`, borderRadius: 8, overflow: "hidden" }}>
            <div style={{ backgroundColor: q.headerBg, padding: "10px 14px" }}>
              <div style={{ color: "#fff", fontWeight: 900, fontSize: 13, letterSpacing: -0.3 }}>{q.label}</div>
              <div style={{ color: "rgba(255,255,255,0.75)", fontSize: 9, fontWeight: 600, textTransform: "uppercase", letterSpacing: 1 }}>{q.subtitle}</div>
            </div>
            <div style={{ backgroundColor: q.lightBg, padding: "12px 14px", minHeight: 140 }}>
              {q.items.length === 0 ? (
                <p style={{ color: "#94a3b8", fontStyle: "italic", fontSize: 10 }}>No items recorded.</p>
              ) : (
                <ul style={{ margin: 0, paddingLeft: 16, lineHeight: 2 }}>
                  {q.items.map((item, i) => (
                    <li key={i} style={{ fontSize: 10, color: "#334155" }}>
                      {item}
                      <span style={{ fontSize: 8, color: "#94a3b8", marginLeft: 6 }}>→ 6.1</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        ))}
      </div>

      <div style={{ marginTop: 20, border: "1px solid #e2e8f0", borderRadius: 8, padding: "12px 14px", backgroundColor: "#f8fafc" }}>
        <p style={{ fontSize: 10, color: "#64748b", margin: 0 }}>
          <strong style={{ color: "#1e3a5f" }}>ISO 4.1 Note:</strong> All items above represent internal context factors. Strengths and opportunities should be leveraged in strategic planning. Weaknesses and threats should be addressed through risk mitigation under Clause 6.1. Use the Ask Isa feature to get AI-guided risk register recommendations based on this SWOT.
        </p>
      </div>

      <DocFooter />
    </div>
  );
}

// ── Interested Parties Document ────────────────────────────────────────────────
function PartiesDocument({ orgName, standard, parties }: { orgName?: string | null; standard?: string | null; parties: InterestedParty[] }) {
  const relevant = parties.filter(p => p.relevant);
  const external = relevant.filter(p => p.group === "external");
  const internal = relevant.filter(p => p.group === "internal");

  const allRows = [
    ...external.map(p => ({ ...p, _groupLabel: "External" })),
    ...internal.map(p => ({ ...p, _groupLabel: "Internal" })),
  ];

  return (
    <div style={{ fontFamily: "'Segoe UI', Arial, sans-serif", fontSize: 10, color: "#0f172a", width: "100%" }}>
      <DocHeader
        title="Interested Parties Register"
        subtitle="Clause 4.2 — Needs, Expectations & Engagement Strategy"
        orgName={orgName}
        standard={standard}
        docRef="ISO-CTXT-4.2-IP"
      />

      {/* Summary */}
      <div style={{ display: "flex", gap: 12, marginBottom: 18 }}>
        {[
          { label: "Total Relevant", value: relevant.length, color: "#1e3a5f" },
          { label: "External", value: external.length, color: "#1d4ed8" },
          { label: "Internal", value: internal.length, color: "#7c3aed" },
        ].map(s => (
          <div key={s.label} style={{ flex: 1, border: "1px solid #e2e8f0", borderRadius: 8, padding: "8px 12px", textAlign: "center" }}>
            <div style={{ fontSize: 18, fontWeight: 900, color: s.color }}>{s.value}</div>
            <div style={{ fontSize: 8, fontWeight: 600, color: "#64748b", textTransform: "uppercase", letterSpacing: 1 }}>{s.label}</div>
          </div>
        ))}
      </div>

      {allRows.length === 0 ? (
        <p style={{ color: "#94a3b8", fontStyle: "italic", textAlign: "center", padding: 30 }}>No relevant interested parties recorded.</p>
      ) : (
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 9 }}>
          <thead>
            <tr style={{ backgroundColor: "#1e3a5f" }}>
              {["Interested Party", "Group", "PI-R Strategy", "Needs", "Expectations", "Actions to Meet Needs", "Monitoring Method", "Assoc. Risks", "Opportunities"].map(h => (
                <th key={h} style={{ padding: "8px 8px", color: "#fff", textAlign: "left", fontWeight: 700, fontSize: 8.5, borderRight: "1px solid rgba(255,255,255,0.15)" }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {allRows.map((p, i) => {
              const isExternal = p.group === "external";
              const pirLabel = PIR_LABELS[p.piRanking] || "—";
              return (
                <tr key={p.id} style={{ backgroundColor: i % 2 === 0 ? "#f8fafc" : "#fff", borderBottom: "1px solid #e2e8f0" }}>
                  <td style={{ padding: "7px 8px", fontWeight: 700, color: "#1e3a5f", verticalAlign: "top", minWidth: 90 }}>{p.party || "—"}</td>
                  <td style={{ padding: "7px 8px", verticalAlign: "top", textAlign: "center" }}>
                    <span style={{
                      display: "inline-block", padding: "2px 6px", borderRadius: 10, fontSize: 8, fontWeight: 700,
                      backgroundColor: isExternal ? "#eff6ff" : "#f5f3ff",
                      color: isExternal ? "#1d4ed8" : "#7c3aed",
                      border: `1px solid ${isExternal ? "#93c5fd" : "#c4b5fd"}`,
                    }}>
                      {p._groupLabel}
                    </span>
                  </td>
                  <td style={{ padding: "7px 8px", verticalAlign: "top", fontWeight: 600, color: "#334155" }}>{pirLabel}</td>
                  <td style={{ padding: "7px 8px", verticalAlign: "top", color: "#475569", lineHeight: 1.4 }}>{p.needs || "—"}</td>
                  <td style={{ padding: "7px 8px", verticalAlign: "top", color: "#475569", lineHeight: 1.4 }}>{p.expectations || "—"}</td>
                  <td style={{ padding: "7px 8px", verticalAlign: "top", color: "#475569", lineHeight: 1.4 }}>{p.actions || "—"}</td>
                  <td style={{ padding: "7px 8px", verticalAlign: "top", color: "#475569", lineHeight: 1.4 }}>{p.monitoringMethod || "—"}</td>
                  <td style={{ padding: "7px 8px", verticalAlign: "top", color: "#dc2626", lineHeight: 1.4 }}>{p.risks || "—"}</td>
                  <td style={{ padding: "7px 8px", verticalAlign: "top", color: "#16a34a", lineHeight: 1.4 }}>{p.opportunities || "—"}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      )}

      {/* PI-R Legend */}
      <div style={{ marginTop: 18, border: "1px solid #e2e8f0", borderRadius: 8, padding: "10px 14px", backgroundColor: "#f8fafc" }}>
        <div style={{ fontWeight: 700, fontSize: 9, color: "#1e3a5f", marginBottom: 6, textTransform: "uppercase", letterSpacing: 1 }}>
          Power &amp; Interest Ranking (PI-R) Legend
        </div>
        <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
          {[
            { key: "Manage Closely", desc: "High Power / High Interest — Engage actively" },
            { key: "Keep Informed", desc: "Low Power / High Interest — Regular communication" },
            { key: "Keep Satisfied", desc: "High Power / Low Interest — Meet their key needs" },
            { key: "Monitor Only", desc: "Low Power / Low Interest — Monitor periodically" },
          ].map(l => (
            <div key={l.key} style={{ fontSize: 8.5, color: "#475569" }}>
              <strong style={{ color: "#1e3a5f" }}>{l.key}:</strong> {l.desc}
            </div>
          ))}
        </div>
      </div>

      <DocFooter />
    </div>
  );
}

// ── Main Export ────────────────────────────────────────────────────────────────
export function ContextPrintDocuments({ docType, onClose, orgName, standard, pestle, swot, parties }: PrintDocsProps) {
  const printRef = useRef<HTMLDivElement>(null);

  if (!docType) return null;

  const handlePrint = () => {
    if (!printRef.current) return;
    const content = printRef.current.innerHTML;
    const win = window.open("", "_blank", "width=900,height=700");
    if (!win) return;
    win.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${docType === "pestle" ? "PESTLE Analysis" : docType === "swot" ? "SWOT Analysis" : "Interested Parties Register"}</title>
          <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body { font-family: 'Segoe UI', Arial, sans-serif; padding: 32px; color: #0f172a; font-size: 10px; }
            @media print {
              body { padding: 16px; }
              @page { margin: 1.2cm; size: ${docType === "parties" ? "A3 landscape" : "A4"}; }
            }
          </style>
        </head>
        <body>${content}</body>
      </html>
    `);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); }, 400);
  };

  const titles: Record<string, string> = {
    pestle: "PESTLE Analysis",
    swot: "SWOT Analysis",
    parties: "Interested Parties Register",
  };

  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-black/60 backdrop-blur-sm">
      {/* Toolbar */}
      <div className="shrink-0 flex items-center justify-between px-6 py-3 bg-white dark:bg-card border-b border-border/60 shadow-sm">
        <div className="flex items-center gap-3">
          <FileText className="w-5 h-5 text-primary" />
          <div>
            <h2 className="font-black text-primary text-sm">{titles[docType]} — Print Preview</h2>
            <p className="text-xs text-muted-foreground">Review your document before printing</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button
            onClick={handlePrint}
            className="bg-primary hover:bg-primary/90 text-white gap-2 h-9 text-sm font-bold"
            data-testid="button-print-document"
          >
            <Printer className="w-4 h-4" />
            Print / Save PDF
          </Button>
          <button
            onClick={onClose}
            className="text-muted-foreground hover:text-primary transition-colors ml-2"
            data-testid="button-close-print-preview"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* Preview area */}
      <div className="flex-1 overflow-auto bg-gray-200 dark:bg-zinc-900 p-8">
        <div
          ref={printRef}
          className="bg-white mx-auto shadow-xl rounded-sm"
          style={{
            width: docType === "parties" ? 1100 : 820,
            padding: "48px 52px",
            minHeight: 1000,
          }}
        >
          {docType === "pestle" && <PestleDocument orgName={orgName} standard={standard} pestle={pestle} />}
          {docType === "swot" && <SwotDocument orgName={orgName} standard={standard} swot={swot} />}
          {docType === "parties" && <PartiesDocument orgName={orgName} standard={standard} parties={parties} />}
        </div>
      </div>
    </div>
  );
}
